Fixed typo

diff --git a/.github/workflows/ansible-configuration-infra.yml b/.github/workflows/ansible-configuration-infra.yml
--- a/.github/workflows/ansible-configuration-infra.yml
+++ b/.github/workflows/ansible-configuration-infra.yml
@@ -36,7 +36,7 @@ jobs:
                 chmod 600 ~/.ssh/ansible_key
                 chmod 700 ~/.ssh
                 echo "=====Validate the key====="
-                ssh-keygen -y -f ~/.ssh/ansible_key > dev/null 2>&1 || (echo "Invalid SSH key format or passphrase-protected key" && exit 1)
+                ssh-keygen -y -f ~/.ssh/ansible_key > /dev/null 2>&1 || (echo "Invalid SSH key format or passphrase-protected key" && exit 1)
                 echo "=========================="
 
 
