Added changes to name of instance + order of github events

diff --git a/.github/workflows/terraform-deploy-infra.yml b/.github/workflows/terraform-deploy-infra.yml
--- a/.github/workflows/terraform-deploy-infra.yml
+++ b/.github/workflows/terraform-deploy-infra.yml
@@ -2,10 +2,10 @@ name: Terraform Deploy Infra
 
 run-name: Terraform Deploy Infra on ${{ inputs.Env }}
 
+#TODO: 
+#
+
 on:
-  push:
-    branches:
-      - test-terraform
   workflow_dispatch:
     inputs:
       Env:
@@ -15,6 +15,9 @@ on:
         options:
           - T1
           - PRD
+  push:
+    branches:
+      - test-terraform
  
 jobs:
   configure-environment:
@@ -68,4 +71,20 @@ jobs:
       - name: Check Terraform Plan 
         working-directory: ./terraform
         if: github.ref == 'refs/heads/test-terraform'
-        run: terraform show -json tfplan | jq .
+        run: terraform show -json tfplan | jq . > plan.json
+
+      - name: Check Terraform Plan for changes
+        working-directory: ./terraform
+        id: check-plan
+        run: |
+          python3 ../utils/check_plan.py plan.json 2> error.log 1> changes.log
+
+          if [ -s error.log ]; then
+            echo "Error while checking plan. Please check number of arguments."
+            cat error.log
+            exit 1
+          else
+            flag=$(head -n 1 changes.log)
+          fi  
+          
+          echo "plan_flag=$flag" >> $GITHUB_OUTPUT
